/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package feesmanagement_system;

import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Rushikesh Sapkale
 */
public class EditCourse extends javax.swing.JFrame {
 DefaultTableModel model;
    /**
     * Creates new form EditCourse
     */
    public EditCourse() {
        initComponents();
        setRecords();
    }
 public void setRecords() {
        try {
            java.sql.Connection con = DBconnection.getConnection();
            PreparedStatement smt = con.prepareStatement("Select * from course ");
            ResultSet rs = smt.executeQuery();
            while(rs.next()){
               String  courseId = rs.getString("Id");
                String cname = rs.getString("Cname");
                String  cost = rs.getString("Cost");
               
                   
                   Object[] obj={courseId,cname,cost};
                  model=(DefaultTableModel) jtbl_coursedata.getModel();
                  model.addRow(obj);
               
               
        }

            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
 public void addCourse(int id, String cname,double cost){
     try {
         Class.forName("com.mysql.cj.jdbc.Driver");

            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees_management?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "system");
           PreparedStatement pst=con.prepareStatement("insert into course values(?,?,?)");
           pst.setInt(1, id);
           pst.setString(2,cname);
           pst.setDouble(3, cost);
            int rowcount=pst.executeUpdate();
            if(rowcount == 1){
                JOptionPane.showMessageDialog(this,"Course Inserted Sucessfully");
                clearTable();
                setRecords();
                
            }else{
             
                JOptionPane.showMessageDialog(this,"Course Inserted failed");
                
            }
     } catch (Exception e) {
          JOptionPane.showMessageDialog(this,"Course Inserted failed");
          e.printStackTrace();
     }
 }
 public void clearTable(){
     DefaultTableModel model=(DefaultTableModel)jtbl_coursedata.getModel();
     model.setRowCount(0);
 }
 public void update(int id, String cname, double cost){
      try {
         Class.forName("com.mysql.cj.jdbc.Driver");

            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees_management?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "system");
           PreparedStatement pst=con.prepareStatement("update  course set cname=?,cost=?where id=?");
           pst.setInt(3, id);
           pst.setString(1,cname);
           pst.setDouble(2, cost);
            int rowcount=pst.executeUpdate();
            if(rowcount == 1){
                JOptionPane.showMessageDialog(this,"Course Updated Sucessfully");
                clearTable();
                setRecords();
                
            }else{
             
                JOptionPane.showMessageDialog(this,"Course Updated failed");
                
            }
     } catch (Exception e) {
          JOptionPane.showMessageDialog(this,"Course Updated failed");
          e.printStackTrace();
     }
     
 }
  public void delete(int id){
      try {
         Class.forName("com.mysql.cj.jdbc.Driver");

            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fees_management?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "system");
           PreparedStatement pst=con.prepareStatement("delete from course where id=?");
           pst.setInt(1, id);
       
            int rowcount=pst.executeUpdate();
            if(rowcount == 1){
                JOptionPane.showMessageDialog(this,"Course Deleted Sucessfully");
                clearTable();
                setRecords();
                
            }else{
             
                JOptionPane.showMessageDialog(this,"Course Deleted failed");
                
            }
     } catch (Exception e) {
          JOptionPane.showMessageDialog(this,"Course Deleted failed");
          e.printStackTrace();
     }
     
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsidebar = new javax.swing.JPanel();
        PANELHOME = new javax.swing.JPanel();
        lblhome = new javax.swing.JLabel();
        PANELHOME1 = new javax.swing.JPanel();
        lblhome1 = new javax.swing.JLabel();
        PANELHOME2 = new javax.swing.JPanel();
        lblhome2 = new javax.swing.JLabel();
        PANELHOME3 = new javax.swing.JPanel();
        lblhome3 = new javax.swing.JLabel();
        PANELHOME4 = new javax.swing.JPanel();
        lblhome4 = new javax.swing.JLabel();
        PANELHOME6 = new javax.swing.JPanel();
        lblhome6 = new javax.swing.JLabel();
        PANELHOME5 = new javax.swing.JPanel();
        lblhome5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_courseid = new javax.swing.JTextField();
        txt_coursename = new javax.swing.JTextField();
        txt_courseprice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_coursedata = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(32767, 32767));

        panelsidebar.setBackground(new java.awt.Color(0, 102, 102));
        panelsidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PANELHOME.setBackground(new java.awt.Color(0, 102, 102));
        PANELHOME.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        PANELHOME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PANELHOMEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PANELHOMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PANELHOMEMouseExited(evt);
            }
        });
        PANELHOME.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhome.setFont(new java.awt.Font("Cambria", 0, 30)); // NOI18N
        lblhome.setForeground(new java.awt.Color(255, 255, 255));
        lblhome.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rushikesh Sapkale\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\images\\search2.png")); // NOI18N
        lblhome.setText("Search Record");
        PANELHOME.add(lblhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 70));

        panelsidebar.add(PANELHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 330, 70));

        PANELHOME1.setBackground(new java.awt.Color(0, 102, 102));
        PANELHOME1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        PANELHOME1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PANELHOME1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PANELHOME1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PANELHOME1MouseExited(evt);
            }
        });
        PANELHOME1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhome1.setFont(new java.awt.Font("Cambria", 0, 30)); // NOI18N
        lblhome1.setForeground(new java.awt.Color(255, 255, 255));
        lblhome1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rushikesh Sapkale\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\images\\edit2.png")); // NOI18N
        lblhome1.setText("Edit Course");
        PANELHOME1.add(lblhome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 70));

        panelsidebar.add(PANELHOME1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 330, 70));

        PANELHOME2.setBackground(new java.awt.Color(0, 102, 102));
        PANELHOME2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        PANELHOME2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PANELHOME2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PANELHOME2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PANELHOME2MouseExited(evt);
            }
        });
        PANELHOME2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhome2.setFont(new java.awt.Font("Cambria", 0, 30)); // NOI18N
        lblhome2.setForeground(new java.awt.Color(255, 255, 255));
        lblhome2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rushikesh Sapkale\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\images\\list_1.png")); // NOI18N
        lblhome2.setText("Edit Details");
        PANELHOME2.add(lblhome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 70));

        panelsidebar.add(PANELHOME2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 330, 70));

        PANELHOME3.setBackground(new java.awt.Color(0, 102, 102));
        PANELHOME3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        PANELHOME3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PANELHOME3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PANELHOME3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PANELHOME3MouseExited(evt);
            }
        });
        PANELHOME3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhome3.setFont(new java.awt.Font("Cambria", 0, 30)); // NOI18N
        lblhome3.setForeground(new java.awt.Color(255, 255, 255));
        lblhome3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rushikesh Sapkale\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\images\\view all record.png")); // NOI18N
        lblhome3.setText("View All Records");
        PANELHOME3.add(lblhome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 70));

        panelsidebar.add(PANELHOME3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 330, 70));

        PANELHOME4.setBackground(new java.awt.Color(0, 102, 102));
        PANELHOME4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        PANELHOME4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PANELHOME4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PANELHOME4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PANELHOME4MouseExited(evt);
            }
        });
        PANELHOME4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhome4.setFont(new java.awt.Font("Cambria", 0, 30)); // NOI18N
        lblhome4.setForeground(new java.awt.Color(255, 255, 255));
        lblhome4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rushikesh Sapkale\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\images\\left-arrow.png")); // NOI18N
        lblhome4.setText("Back");
        PANELHOME4.add(lblhome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 70));

        panelsidebar.add(PANELHOME4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 330, 70));

        PANELHOME6.setBackground(new java.awt.Color(0, 102, 102));
        PANELHOME6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        PANELHOME6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PANELHOME6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PANELHOME6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PANELHOME6MouseExited(evt);
            }
        });
        PANELHOME6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhome6.setFont(new java.awt.Font("Cambria", 0, 30)); // NOI18N
        lblhome6.setForeground(new java.awt.Color(255, 255, 255));
        lblhome6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rushikesh Sapkale\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\images\\home.png")); // NOI18N
        lblhome6.setText("Home");
        PANELHOME6.add(lblhome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 70));

        panelsidebar.add(PANELHOME6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 330, 70));

        PANELHOME5.setBackground(new java.awt.Color(0, 102, 102));
        PANELHOME5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        PANELHOME5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PANELHOME5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PANELHOME5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PANELHOME5MouseExited(evt);
            }
        });
        PANELHOME5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhome5.setFont(new java.awt.Font("Cambria", 0, 30)); // NOI18N
        lblhome5.setForeground(new java.awt.Color(255, 255, 255));
        lblhome5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rushikesh Sapkale\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\images\\logout.png")); // NOI18N
        lblhome5.setText("Logout");
        PANELHOME5.add(lblhome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 70));

        panelsidebar.add(PANELHOME5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 330, 70));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Edit Course Details");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Course Name:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Course Price:");

        txt_courseid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_courseid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_courseidActionPerformed(evt);
            }
        });

        txt_coursename.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_coursename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_coursenameActionPerformed(evt);
            }
        });

        txt_courseprice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_courseprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_coursepriceActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jtbl_coursedata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Id", "Course Name", "Course Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_coursedata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_coursedataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbl_coursedata);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Course Id:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rushikesh Sapkale\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\images\\back-button.png")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_coursename, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(txt_courseprice, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(txt_courseid))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton2)
                        .addGap(29, 29, 29)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_courseid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_coursename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_courseprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelsidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelsidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PANELHOMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOMEMouseEntered
        Color clr = new Color(0, 153, 152);
        PANELHOME.setBackground(clr);
    }//GEN-LAST:event_PANELHOMEMouseEntered

    private void PANELHOMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOMEMouseExited
        Color clr = new Color(0, 103, 103);
        PANELHOME.setBackground(clr);
    }//GEN-LAST:event_PANELHOMEMouseExited

    private void PANELHOME1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME1MouseEntered
        Color clr = new Color(0, 153, 152);
        PANELHOME1.setBackground(clr); // TODO add your handling code here:
    }//GEN-LAST:event_PANELHOME1MouseEntered

    private void PANELHOME1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME1MouseExited
        Color clr = new Color(0, 103, 103);
        PANELHOME1.setBackground(clr); // TODO add your handling code here:
    }//GEN-LAST:event_PANELHOME1MouseExited

    private void PANELHOME2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME2MouseEntered
        Color clr = new Color(0, 153, 152);
        PANELHOME2.setBackground(clr); // TODO add your handling code here:
    }//GEN-LAST:event_PANELHOME2MouseEntered

    private void PANELHOME2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME2MouseExited
        Color clr = new Color(0, 103, 103);
        PANELHOME2.setBackground(clr); // TODO add your handling code here:
    }//GEN-LAST:event_PANELHOME2MouseExited

    private void PANELHOME3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME3MouseEntered
        Color clr = new Color(0, 153, 152);
        PANELHOME3.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_PANELHOME3MouseEntered

    private void PANELHOME3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME3MouseExited
        Color clr = new Color(0, 103, 103);
        PANELHOME3.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_PANELHOME3MouseExited

    private void PANELHOME4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME4MouseEntered
        Color clr = new Color(0, 153, 152);
        PANELHOME4.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_PANELHOME4MouseEntered

    private void PANELHOME4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME4MouseExited
        Color clr = new Color(0, 103, 103);
        PANELHOME4.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_PANELHOME4MouseExited

    private void PANELHOME6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME6MouseEntered

        Color clr = new Color(0, 153, 152);
        PANELHOME6.setBackground(clr);
    }//GEN-LAST:event_PANELHOME6MouseEntered

    private void PANELHOME6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME6MouseExited
        Color clr = new Color(0, 103, 103);
        PANELHOME6.setBackground(clr);
    }//GEN-LAST:event_PANELHOME6MouseExited

    private void PANELHOME5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME5MouseEntered
        Color clr = new Color(0, 153, 152);
        PANELHOME5.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_PANELHOME5MouseEntered

    private void PANELHOME5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME5MouseExited
        Color clr = new Color(0, 103, 103);
        PANELHOME5.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_PANELHOME5MouseExited

    private void txt_courseidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_courseidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_courseidActionPerformed

    private void txt_coursenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_coursenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_coursenameActionPerformed

    private void txt_coursepriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_coursepriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_coursepriceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int id=Integer.parseInt(txt_courseid.getText());
       String cname=txt_coursename.getText();
       double cost=Double.parseDouble(txt_courseprice.getText());
       
        addCourse(id, cname, cost);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int id=Integer.parseInt(txt_courseid.getText());
       String cname=txt_coursename.getText();
       double cost=Double.parseDouble(txt_courseprice.getText());
       
        update(id, cname, cost);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          int id=Integer.parseInt(txt_courseid.getText());
       String cname=txt_coursename.getText();
       double cost=Double.parseDouble(txt_courseprice.getText());
       
      delete(id);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtbl_coursedataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_coursedataMouseClicked
      int rowNO=  jtbl_coursedata.getSelectedRow();
        TableModel model= jtbl_coursedata.getModel();
        
        txt_courseid.setText(model.getValueAt(rowNO, 0).toString());
        txt_coursename.setText(model.getValueAt(rowNO, 1).toString());
        txt_courseprice.setText(model.getValueAt(rowNO, 2).toString()); 
        
    }//GEN-LAST:event_jtbl_coursedataMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
     
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Home home =new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void PANELHOME6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME6MouseClicked
       Home home =new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PANELHOME6MouseClicked

    private void PANELHOMEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOMEMouseClicked
               SearchRecord searchRecord =new SearchRecord();
        searchRecord.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PANELHOMEMouseClicked

    private void PANELHOME1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME1MouseClicked
            EditCourse editCourse =new EditCourse();
        editCourse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PANELHOME1MouseClicked

    private void PANELHOME3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME3MouseClicked
       ViewAllRecords viewAllRecords=new ViewAllRecords();
       viewAllRecords.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_PANELHOME3MouseClicked

    private void PANELHOME4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME4MouseClicked
        Home home =new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PANELHOME4MouseClicked

    private void PANELHOME5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME5MouseClicked
       Login login =new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PANELHOME5MouseClicked

    private void PANELHOME2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME2MouseClicked
       UpdateFeesDetails updateFeesDetails=new UpdateFeesDetails();
      updateFeesDetails.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_PANELHOME2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PANELHOME;
    private javax.swing.JPanel PANELHOME1;
    private javax.swing.JPanel PANELHOME2;
    private javax.swing.JPanel PANELHOME3;
    private javax.swing.JPanel PANELHOME4;
    private javax.swing.JPanel PANELHOME5;
    private javax.swing.JPanel PANELHOME6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbl_coursedata;
    private javax.swing.JLabel lblhome;
    private javax.swing.JLabel lblhome1;
    private javax.swing.JLabel lblhome2;
    private javax.swing.JLabel lblhome3;
    private javax.swing.JLabel lblhome4;
    private javax.swing.JLabel lblhome5;
    private javax.swing.JLabel lblhome6;
    private javax.swing.JPanel panelsidebar;
    private javax.swing.JTextField txt_courseid;
    private javax.swing.JTextField txt_coursename;
    private javax.swing.JTextField txt_courseprice;
    // End of variables declaration//GEN-END:variables
}
