/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package feesmanagement_system;


import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.*;
import java.sql.PreparedStatement;

/**
 *
 * @author Rushikesh Sapkale
 */
public class PrintReceipt extends javax.swing.JFrame {

    /**
     * Creates new form PrintReceipt
     */
    public PrintReceipt() {
        initComponents();
      getRecords();
       
        
    }

    public void getRecords() {
        try {
            Connection con = DBconnection.getConnection();
            PreparedStatement smt = con.prepareStatement("Select * from fees_detail order by reciept_no desc limit 1");
            ResultSet rs = smt.executeQuery();
            rs.next();

            txtrecieptno.setText(rs.getString("reciept_no"));
            txtroll.setText(rs.getString("rollno"));
            txtReceiver.setText(rs.getString("student_name"));
            txtpaymode.setText(rs.getString("payment_mode"));
            txtCheque.setText(rs.getString("cheque_no"));
            txtbankname.setText(rs.getString("bank_name"));
            txtcorse.setText(rs.getString("course"));
            txthead.setText(rs.getString("course"));
            txtGstn.setText(rs.getString("gstin"));
            txttotalamt.setText(rs.getString("amount"));
            txtdate.setText(rs.getString("date"));
            txtamount.setText(rs.getString("total_amount"));
            txtcgst.setText(rs.getString("cgst"));
            txtsgst.setText(rs.getString("sgst"));
            txttotalinwords1.setText(rs.getString("totalinwords"));
            txtremark.setText(rs.getString("remark"));
            year1.setText(rs.getString("year1"));
            year2.setText(rs.getString("year2"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelsidebar = new javax.swing.JPanel();
        PANELHOME = new javax.swing.JPanel();
        lblhome = new javax.swing.JLabel();
        PANELHOME1 = new javax.swing.JPanel();
        lblhome1 = new javax.swing.JLabel();
        PANELHOME2 = new javax.swing.JPanel();
        lblhome2 = new javax.swing.JLabel();
        PANELHOME3 = new javax.swing.JPanel();
        lblhome3 = new javax.swing.JLabel();
        PANELHOME4 = new javax.swing.JPanel();
        lblhome4 = new javax.swing.JLabel();
        PANELHOME6 = new javax.swing.JPanel();
        lblhome6 = new javax.swing.JLabel();
        PANELHOME8 = new javax.swing.JPanel();
        lblhome8 = new javax.swing.JLabel();
        PANELHOME9 = new javax.swing.JPanel();
        lblhome9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelprint = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txthead = new javax.swing.JLabel();
        txtrecieptno = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtpaymode = new javax.swing.JLabel();
        txtCheque = new javax.swing.JLabel();
        txtbankname = new javax.swing.JLabel();
        txtReceiver = new javax.swing.JLabel();
        txtdate = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtGstn = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtremark = new javax.swing.JLabel();
        txtamount = new javax.swing.JLabel();
        txtcgst = new javax.swing.JLabel();
        txtsgst = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        year2 = new javax.swing.JLabel();
        txtcorse = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtroll = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txttotalamt = new javax.swing.JLabel();
        txttotalinwords1 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        year1 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        Editbtn = new javax.swing.JPanel();
        lblhome5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelsidebar.setBackground(new java.awt.Color(0, 102, 102));
        panelsidebar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelsidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PANELHOME.setBackground(new java.awt.Color(0, 102, 102));
        PANELHOME.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        PANELHOME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PANELHOMEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PANELHOMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PANELHOMEMouseExited(evt);
            }
        });
        PANELHOME.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhome.setFont(new java.awt.Font("Cambria", 0, 30)); // NOI18N
        lblhome.setForeground(new java.awt.Color(255, 255, 255));
        lblhome.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rushikesh Sapkale\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\images\\search2.png")); // NOI18N
        lblhome.setText("Search Record");
        PANELHOME.add(lblhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 70));

        panelsidebar.add(PANELHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 330, 60));

        PANELHOME1.setBackground(new java.awt.Color(0, 102, 102));
        PANELHOME1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        PANELHOME1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PANELHOME1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PANELHOME1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PANELHOME1MouseExited(evt);
            }
        });
        PANELHOME1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhome1.setFont(new java.awt.Font("Cambria", 0, 30)); // NOI18N
        lblhome1.setForeground(new java.awt.Color(255, 255, 255));
        lblhome1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rushikesh Sapkale\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\images\\edit2.png")); // NOI18N
        lblhome1.setText("Edit Course");
        PANELHOME1.add(lblhome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 70));

        panelsidebar.add(PANELHOME1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 330, 70));

        PANELHOME2.setBackground(new java.awt.Color(0, 102, 102));
        PANELHOME2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        PANELHOME2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PANELHOME2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PANELHOME2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PANELHOME2MouseExited(evt);
            }
        });
        PANELHOME2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhome2.setFont(new java.awt.Font("Cambria", 0, 30)); // NOI18N
        lblhome2.setForeground(new java.awt.Color(255, 255, 255));
        lblhome2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rushikesh Sapkale\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\images\\list_1.png")); // NOI18N
        lblhome2.setText("Edit Details");
        PANELHOME2.add(lblhome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 70));

        panelsidebar.add(PANELHOME2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 330, 60));

        PANELHOME3.setBackground(new java.awt.Color(0, 102, 102));
        PANELHOME3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        PANELHOME3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PANELHOME3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PANELHOME3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PANELHOME3MouseExited(evt);
            }
        });
        PANELHOME3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhome3.setFont(new java.awt.Font("Cambria", 0, 30)); // NOI18N
        lblhome3.setForeground(new java.awt.Color(255, 255, 255));
        lblhome3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rushikesh Sapkale\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\images\\view all record.png")); // NOI18N
        lblhome3.setText("View All Records");
        PANELHOME3.add(lblhome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 70));

        panelsidebar.add(PANELHOME3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 330, 60));

        PANELHOME4.setBackground(new java.awt.Color(0, 102, 102));
        PANELHOME4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        PANELHOME4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PANELHOME4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PANELHOME4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PANELHOME4MouseExited(evt);
            }
        });
        PANELHOME4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhome4.setFont(new java.awt.Font("Cambria", 0, 30)); // NOI18N
        lblhome4.setForeground(new java.awt.Color(255, 255, 255));
        lblhome4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rushikesh Sapkale\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\images\\left-arrow.png")); // NOI18N
        lblhome4.setText("Back");
        PANELHOME4.add(lblhome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 70));

        panelsidebar.add(PANELHOME4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 330, 60));

        PANELHOME6.setBackground(new java.awt.Color(0, 102, 102));
        PANELHOME6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        PANELHOME6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PANELHOME6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PANELHOME6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PANELHOME6MouseExited(evt);
            }
        });
        PANELHOME6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhome6.setFont(new java.awt.Font("Cambria", 0, 30)); // NOI18N
        lblhome6.setForeground(new java.awt.Color(255, 255, 255));
        lblhome6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rushikesh Sapkale\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\images\\home.png")); // NOI18N
        lblhome6.setText("Home");
        PANELHOME6.add(lblhome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 70));

        panelsidebar.add(PANELHOME6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 330, 60));

        PANELHOME8.setBackground(new java.awt.Color(0, 102, 102));
        PANELHOME8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        PANELHOME8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PANELHOME8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PANELHOME8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PANELHOME8MouseExited(evt);
            }
        });
        PANELHOME8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhome8.setFont(new java.awt.Font("Cambria", 0, 30)); // NOI18N
        lblhome8.setForeground(new java.awt.Color(255, 255, 255));
        lblhome8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rushikesh Sapkale\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\images\\logout.png")); // NOI18N
        lblhome8.setText("Logout");
        PANELHOME8.add(lblhome8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 70));

        panelsidebar.add(PANELHOME8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 330, 60));

        PANELHOME9.setBackground(new java.awt.Color(0, 102, 102));
        PANELHOME9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        PANELHOME9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PANELHOME9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PANELHOME9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PANELHOME9MouseExited(evt);
            }
        });
        PANELHOME9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhome9.setFont(new java.awt.Font("Cambria", 0, 30)); // NOI18N
        lblhome9.setForeground(new java.awt.Color(255, 255, 255));
        lblhome9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rushikesh Sapkale\\Downloads\\my icons\\my icons\\printer-.png")); // NOI18N
        lblhome9.setText("Print");
        lblhome9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhome9MouseClicked(evt);
            }
        });
        PANELHOME9.add(lblhome9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 70));

        panelsidebar.add(PANELHOME9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 330, 60));

        panelprint.setBackground(new java.awt.Color(255, 255, 255));
        panelprint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setText("(Vadgoan Budruk Pune -411 041)");
        panelprint.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, 30));

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel2.setText("STES's  Smt. Kashibai Navle College of Engineering");
        panelprint.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 550, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rushikesh Sapkale\\OneDrive\\Desktop\\BESE IT\\sinhgad-logo-colour-1.png")); // NOI18N
        panelprint.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 180, 100));
        panelprint.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1260, 10));

        txthead.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txthead.setText("1");
        panelprint.add(txthead, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 700, 80, -1));

        txtrecieptno.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtrecieptno.setText("jLabel6");
        panelprint.add(txtrecieptno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel7.setText("SKN");
        panelprint.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        txtpaymode.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtpaymode.setText("jLabel8");
        panelprint.add(txtpaymode, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        txtCheque.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtCheque.setText("Cheque No. :");
        panelprint.add(txtCheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        txtbankname.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtbankname.setText("Bank Name :");
        panelprint.add(txtbankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        txtReceiver.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtReceiver.setText("Recive From :");
        panelprint.add(txtReceiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 280, -1));

        txtdate.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtdate.setText("Date :");
        panelprint.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 160, 120, -1));
        panelprint.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 1260, 20));
        panelprint.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 587, 1210, -1));

        txtGstn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtGstn.setText("GSTIN :");
        panelprint.add(txtGstn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, 160, -1));

        jLabel14.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel14.setText("Sr No.");
        panelprint.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, -1, -1));

        jLabel15.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel15.setText("Head");
        panelprint.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 610, -1, -1));

        jLabel16.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel16.setText("Amount");
        panelprint.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 610, -1, -1));

        jLabel17.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel17.setText("1");
        panelprint.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 710, -1, -1));

        txtremark.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtremark.setText("Total In Words :");
        panelprint.add(txtremark, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 990, 230, -1));

        txtamount.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtamount.setText("CGST");
        panelprint.add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 690, 130, -1));

        txtcgst.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtcgst.setText("SGST");
        panelprint.add(txtcgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 770, 130, -1));

        txtsgst.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtsgst.setText("SGST");
        panelprint.add(txtsgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 840, 130, -1));

        jLabel22.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel22.setText("CGST(9%)");
        panelprint.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 780, 130, -1));

        jLabel23.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel23.setText("Reciept No.");
        panelprint.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel24.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel24.setText("Payment Mode :");
        panelprint.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel25.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel25.setText("Cheque No. :");
        panelprint.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        year2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        year2.setText("Year :");
        panelprint.add(year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 80, -1));

        txtcorse.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtcorse.setText("Course :");
        panelprint.add(txtcorse, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, -1, -1));

        jLabel28.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel28.setText("Date :");
        panelprint.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, -1, -1));

        txtroll.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtroll.setText("Enrollment No. :");
        panelprint.add(txtroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 250, -1, -1));

        jLabel30.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel30.setText("SGST(9%)");
        panelprint.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 850, 130, -1));

        jLabel31.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel31.setText("Receiver Signature");
        panelprint.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 990, 180, 30));

        jLabel32.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel32.setText("Total In Words :");
        panelprint.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 900, 160, -1));

        jLabel33.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel33.setText("Remark :");
        panelprint.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 990, 80, -1));
        panelprint.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 980, 390, 30));
        panelprint.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 890, 400, 30));

        txttotalamt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txttotalamt.setText("Remark :");
        panelprint.add(txttotalamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 900, 200, -1));

        txttotalinwords1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txttotalinwords1.setText("Total In Words :");
        panelprint.add(txttotalinwords1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 900, 440, -1));

        jLabel34.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel34.setText("Bank Name :");
        panelprint.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel35.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel35.setText("The following payment the collage office for the year :");
        panelprint.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, 30));

        year1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        year1.setText("Year :");
        panelprint.add(year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 80, -1));

        jLabel37.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel37.setText("to");
        panelprint.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 80, -1));

        jLabel36.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel36.setText("Recive From :");
        panelprint.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabel38.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel38.setText("Course :");
        panelprint.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, -1, -1));

        jLabel39.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel39.setText("GSTIN :");
        panelprint.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, -1, -1));

        jLabel40.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel40.setText("Enrollment No. :");
        panelprint.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, -1, -1));

        jScrollPane2.setViewportView(panelprint);

        panelsidebar.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 1140, 680));

        Editbtn.setBackground(new java.awt.Color(0, 102, 102));
        Editbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 204, 204), null, null));
        Editbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditbtnMouseExited(evt);
            }
        });
        Editbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhome5.setFont(new java.awt.Font("Cambria", 0, 30)); // NOI18N
        lblhome5.setForeground(new java.awt.Color(255, 255, 255));
        lblhome5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rushikesh Sapkale\\OneDrive\\Documents\\NetBeansProjects\\Fees_Management_System\\src\\main\\java\\com\\mycompany\\fees_management_system\\images\\edit2.png")); // NOI18N
        lblhome5.setText("Edit ");
        Editbtn.add(lblhome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 70));

        panelsidebar.add(Editbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 330, 60));

        jScrollPane1.setViewportView(panelsidebar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1749, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1376, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PANELHOMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOMEMouseEntered
        Color clr = new Color(0, 153, 152);
        PANELHOME.setBackground(clr);
    }//GEN-LAST:event_PANELHOMEMouseEntered

    private void PANELHOMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOMEMouseExited
        Color clr = new Color(0, 103, 103);
        PANELHOME.setBackground(clr);
    }//GEN-LAST:event_PANELHOMEMouseExited

    private void PANELHOME1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME1MouseEntered
        Color clr = new Color(0, 153, 152);
        PANELHOME1.setBackground(clr); // TODO add your handling code here:
    }//GEN-LAST:event_PANELHOME1MouseEntered

    private void PANELHOME1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME1MouseExited
        Color clr = new Color(0, 103, 103);
        PANELHOME1.setBackground(clr); // TODO add your handling code here:
    }//GEN-LAST:event_PANELHOME1MouseExited

    private void PANELHOME2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME2MouseEntered
        Color clr = new Color(0, 153, 152);
        PANELHOME2.setBackground(clr); // TODO add your handling code here:
    }//GEN-LAST:event_PANELHOME2MouseEntered

    private void PANELHOME2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME2MouseExited
        Color clr = new Color(0, 103, 103);
        PANELHOME2.setBackground(clr); // TODO add your handling code here:
    }//GEN-LAST:event_PANELHOME2MouseExited

    private void PANELHOME3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME3MouseEntered
        Color clr = new Color(0, 153, 152);
        PANELHOME3.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_PANELHOME3MouseEntered

    private void PANELHOME3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME3MouseExited
        Color clr = new Color(0, 103, 103);
        PANELHOME3.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_PANELHOME3MouseExited

    private void PANELHOME4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME4MouseEntered
        Color clr = new Color(0, 153, 152);
        PANELHOME4.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_PANELHOME4MouseEntered

    private void PANELHOME4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME4MouseExited
        Color clr = new Color(0, 103, 103);
        PANELHOME4.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_PANELHOME4MouseExited

    private void PANELHOME8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME8MouseEntered
        Color clr = new Color(0, 153, 152);
        PANELHOME8.setBackground(clr);   
    }//GEN-LAST:event_PANELHOME8MouseEntered

    private void PANELHOME8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME8MouseExited
    Color clr = new Color(0, 103, 103);
        PANELHOME8.setBackground(clr);        // TODO add your handling code here:
                                          
    }//GEN-LAST:event_PANELHOME8MouseExited

    private void PANELHOME9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME9MouseEntered
        Color clr = new Color(0, 153, 152);
        PANELHOME9.setBackground(clr);   
    }//GEN-LAST:event_PANELHOME9MouseEntered

    private void PANELHOME9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME9MouseExited
          Color clr = new Color(0, 103, 103);
        PANELHOME9.setBackground(clr); 
    }//GEN-LAST:event_PANELHOME9MouseExited

    private void lblhome9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhome9MouseClicked
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                panelprint.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
    }//GEN-LAST:event_lblhome9MouseClicked

    private void PANELHOME6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME6MouseExited
        Color clr = new Color(0, 103, 103);
        PANELHOME6.setBackground(clr);
    }//GEN-LAST:event_PANELHOME6MouseExited

    private void PANELHOME6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME6MouseEntered

        Color clr = new Color(0, 153, 152);
        PANELHOME6.setBackground(clr);
    }//GEN-LAST:event_PANELHOME6MouseEntered

    private void EditbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditbtnMouseEntered
Color clr = new Color(0, 153, 153);
        Editbtn.setBackground(clr);         // TODO add your handling code here:
    }//GEN-LAST:event_EditbtnMouseEntered

    private void EditbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditbtnMouseExited
Color clr = new Color(0, 103, 103);
        Editbtn.setBackground(clr);         // TODO add your handling code here:
    }//GEN-LAST:event_EditbtnMouseExited

    private void EditbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditbtnMouseClicked
       UpdateFeesDetails u=new UpdateFeesDetails();
       u.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_EditbtnMouseClicked

    private void PANELHOME6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME6MouseClicked
     Home home=new Home();
     home.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_PANELHOME6MouseClicked

    private void PANELHOMEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOMEMouseClicked
       SearchRecord searchRecord=new SearchRecord();
      searchRecord.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_PANELHOMEMouseClicked

    private void PANELHOME1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME1MouseClicked
         EditCourse editCourse=new EditCourse();
        editCourse.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PANELHOME1MouseClicked

    private void PANELHOME3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME3MouseClicked
        ViewAllRecords viewAllRecords=new ViewAllRecords();
        viewAllRecords.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PANELHOME3MouseClicked

    private void PANELHOME4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME4MouseClicked
        AddFees addFees=new AddFees();
       addFees.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_PANELHOME4MouseClicked

    private void PANELHOME8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME8MouseClicked
       Login login=new Login();
      login.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_PANELHOME8MouseClicked

    private void PANELHOME9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME9MouseClicked
      AddFees addFees=new AddFees();
       addFees.setVisible(true);
       this.dispose();        
    }//GEN-LAST:event_PANELHOME9MouseClicked

    private void PANELHOME2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PANELHOME2MouseClicked
      
        UpdateFeesDetails updateFeesDetails=new UpdateFeesDetails();
      updateFeesDetails.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_PANELHOME2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Editbtn;
    private javax.swing.JPanel PANELHOME;
    private javax.swing.JPanel PANELHOME1;
    private javax.swing.JPanel PANELHOME2;
    private javax.swing.JPanel PANELHOME3;
    private javax.swing.JPanel PANELHOME4;
    private javax.swing.JPanel PANELHOME6;
    private javax.swing.JPanel PANELHOME8;
    private javax.swing.JPanel PANELHOME9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblhome;
    private javax.swing.JLabel lblhome1;
    private javax.swing.JLabel lblhome2;
    private javax.swing.JLabel lblhome3;
    private javax.swing.JLabel lblhome4;
    private javax.swing.JLabel lblhome5;
    private javax.swing.JLabel lblhome6;
    private javax.swing.JLabel lblhome8;
    private javax.swing.JLabel lblhome9;
    private javax.swing.JPanel panelprint;
    private javax.swing.JPanel panelsidebar;
    private javax.swing.JLabel txtCheque;
    private javax.swing.JLabel txtGstn;
    private javax.swing.JLabel txtReceiver;
    private javax.swing.JLabel txtamount;
    private javax.swing.JLabel txtbankname;
    private javax.swing.JLabel txtcgst;
    private javax.swing.JLabel txtcorse;
    private javax.swing.JLabel txtdate;
    private javax.swing.JLabel txthead;
    private javax.swing.JLabel txtpaymode;
    private javax.swing.JLabel txtrecieptno;
    private javax.swing.JLabel txtremark;
    private javax.swing.JLabel txtroll;
    private javax.swing.JLabel txtsgst;
    private javax.swing.JLabel txttotalamt;
    private javax.swing.JLabel txttotalinwords1;
    private javax.swing.JLabel year1;
    private javax.swing.JLabel year2;
    // End of variables declaration//GEN-END:variables
}
